language: java

script:
  - mvn clean package
  - mvn sonar:sonar -Dsonar.projectKey=Byte-Size-Games-Back-End -Dsonar.organization=1905-uta-java -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=181420da6e9a7a0bd9b5360f1a94031694dc9bbf


